#!/usr/bin/env python3
"""Read the Cloudflare R2 upload manifest produced by hartfelt_r2_uploader.py
and upsert `r2_key_en` / `r2_key_es` into the Supabase `training_videos` table.

This is the R2 replacement for scripts/sync_youtube_ids.py.

Usage
-----
    python3 scripts/sync_r2_keys.py \
        --manifest "/.../_Render_Logs/hartfelt_r2_manifest.json" \
        --supabase-url "$NEXT_PUBLIC_SUPABASE_URL" \
        --supabase-key "$SUPABASE_SERVICE_ROLE_KEY" \
        [--dry-run] [--out-sql updates.sql]

Manifest shape (a list of dicts under "videos"):
    {
      "bucket": "hartfelt-training",
      "videos": [
        {
          "key": "training/vol1/en/module_01/v1.1.mp4",
          "volume": 1, "lang": "en", "module": 1,
          "major": 1, "minor": "1", "video_num": "1.1",
          ...
        },
        ...
      ]
    }

The script groups entries by (volume, video_num) so each training_videos row
gets both its EN and ES key in a single UPDATE.
"""
from __future__ import annotations

import argparse
import json
import sys
from collections import defaultdict
from typing import Dict, Tuple
from urllib.parse import urlencode
from urllib.request import Request, urlopen
from urllib.error import HTTPError


def load_manifest(path: str) -> dict:
    with open(path, "r") as f:
        return json.load(f)


def build_key_map(manifest: dict) -> Dict[Tuple[int, str], Dict[str, str]]:
    """(volume, video_num) -> {en: key, es: key}"""
    out: Dict[Tuple[int, str], Dict[str, str]] = defaultdict(dict)
    for v in manifest.get("videos", []):
        vol = int(v["volume"])
        vnum = v["video_num"]
        lang = v["lang"]
        out[(vol, vnum)][lang] = v["key"]
    return out


def emit_sql(mapping: Dict[Tuple[int, str], Dict[str, str]]) -> list:
    statements = []
    for (vol, vnum), langs in sorted(mapping.items()):
        sets = []
        if "en" in langs:
            sets.append(f"r2_key_en = '{langs['en']}'")
        if "es" in langs:
            sets.append(f"r2_key_es = '{langs['es']}'")
        if not sets:
            continue
        statements.append(
            f"UPDATE public.training_videos "
            f"SET {', '.join(sets)}, updated_at = NOW() "
            f"WHERE volume = {vol} AND video_num = '{vnum}';"
        )
    return statements


def patch_supabase(
    supabase_url: str,
    supabase_key: str,
    mapping: Dict[Tuple[int, str], Dict[str, str]],
) -> None:
    ok = 0
    fail = 0
    for (vol, vnum), langs in sorted(mapping.items()):
        body = {}
        if "en" in langs:
            body["r2_key_en"] = langs["en"]
        if "es" in langs:
            body["r2_key_es"] = langs["es"]
        if not body:
            continue
        qs = urlencode({"volume": f"eq.{vol}", "video_num": f"eq.{vnum}"})
        url = f"{supabase_url.rstrip('/')}/rest/v1/training_videos?{qs}"
        req = Request(
            url,
            data=json.dumps(body).encode(),
            headers={
                "Content-Type": "application/json",
                "apikey": supabase_key,
                "Authorization": f"Bearer {supabase_key}",
                "Prefer": "return=minimal",
            },
            method="PATCH",
        )
        try:
            urlopen(req)
            ok += 1
            print(f"  OK  v{vol} {vnum}")
        except HTTPError as e:
            fail += 1
            print(f"  FAIL v{vol} {vnum}: {e.code} {e.read().decode(errors='ignore')[:200]}")
        except Exception as e:
            fail += 1
            print(f"  FAIL v{vol} {vnum}: {e}")
    print(f"\nApplied {ok} updates, {fail} failures")


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--manifest", required=True)
    ap.add_argument("--supabase-url")
    ap.add_argument("--supabase-key")
    ap.add_argument("--dry-run", action="store_true")
    ap.add_argument("--out-sql", help="Write UPDATE statements to a .sql file")
    args = ap.parse_args()

    manifest = load_manifest(args.manifest)
    mapping = build_key_map(manifest)
    print(f"Manifest has {len(mapping)} unique (volume, video_num) pairs")

    statements = emit_sql(mapping)
    print(f"Generated {len(statements)} UPDATE statements")

    if args.out_sql:
        with open(args.out_sql, "w") as f:
            f.write("-- Auto-generated by sync_r2_keys.py\n")
            f.write("\n".join(statements) + "\n")
        print(f"Wrote SQL to {args.out_sql}")

    if args.dry_run:
        print("\n--- DRY RUN: first 5 UPDATEs ---")
        for s in statements[:5]:
            print(s)
        return 0

    if not args.supabase_url or not args.supabase_key:
        print(
            "ERROR: provide --supabase-url and --supabase-key (or use --dry-run)",
            file=sys.stderr,
        )
        return 1

    patch_supabase(args.supabase_url, args.supabase_key, mapping)
    return 0


if __name__ == "__main__":
    sys.exit(main())
